name: Generate Stats

on:
  schedule:
    - cron: "0 */12 * * *"  # Every 12 hours
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Heang-Dev
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Phnom_Penh

          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used

          filename: github-stats.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update github stats"

      - name: Generate Isocalendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Heang-Dev
          template: classic
          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          filename: isocalendar.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update isocalendar"

      - name: Generate Achievements
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Heang-Dev
          template: classic
          base: ""

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_threshold: B
          plugin_achievements_secrets: yes
          plugin_achievements_limit: 6

          filename: achievements.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update achievements"

      - name: Generate Streak Calendar
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Heang-Dev
          template: classic
          base: ""
          config_timezone: Asia/Phnom_Penh

          plugin_calendar: yes
          plugin_calendar_limit: 1

          plugin_habits: yes
          plugin_habits_from: 200
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: classic

          filename: streak.svg
          output_action: commit
          committer_branch: main
          committer_message: "chore: update streak"
